import Link from 'next/link';
import { loadEntryDetail } from '@/lib/entry-detail';
import { loadCompRecapTrend, type TestTrendSeries } from '@/lib/comp-recap-companion';
import { EntryDetailView } from '@/components/entry-detail/EntryDetailView';
import { TestTrendView } from '@/components/entry-detail/TestTrendView';

export const dynamic = 'force-dynamic';

export default async function EntryDetailPage({
  params,
}: {
  params: Promise<{ type: string; id: string }>;
}) {
  const { type, id } = await params;
  const detail = await loadEntryDetail(type, id);

  if (!detail) {
    return (
      <main className="mx-auto max-w-4xl px-6 py-8">
        <h1 className="text-2xl font-semibold tracking-tight">Entry not found</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          This entry doesn’t exist, was deleted, or the type isn’t recognized.
        </p>
        <p className="mt-6">
          <Link
            href={'/entries/list' as never}
            className="text-sm text-primary underline-offset-4 hover:underline"
          >
            ← Back to entries
          </Link>
        </p>
      </main>
    );
  }

  const isDraft = String(detail.row.entry_state ?? 'complete') === 'draft';
  const isDecisionLog = type === 'decision_log';
  const extras = (detail.row.extras ?? {}) as Record<string, unknown>;
  const outcome = {
    actual_outcome: extras.actual_outcome ? String(extras.actual_outcome) : '',
    delta: extras.delta ? String(extras.delta) : '',
    learned: extras.learned ? String(extras.learned) : '',
  };
  const hasOutcome = Boolean(outcome.actual_outcome || outcome.delta || outcome.learned);

  // Comp Recap companion view (SOP-04): the Test Log trend for the event
  // window, computed for display — never stored on the recap.
  let trend: TestTrendSeries[] = [];
  if (type === 'comp_recap') {
    trend = await loadCompRecapTrend(
      typeof detail.row.comp_start_date === 'string' ? detail.row.comp_start_date : null,
      typeof detail.row.comp_end_date === 'string' ? detail.row.comp_end_date : null,
    );
  }

  return (
    <main className="mx-auto max-w-4xl px-6 py-8">
      <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-4">
        <div className="flex flex-wrap items-center gap-3">
          <h1 className="text-2xl font-semibold tracking-tight">{detail.definition.label}</h1>
          <span
            className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${
              isDraft ? 'bg-amber-100 text-amber-900' : 'bg-emerald-100 text-emerald-900'
            }`}
          >
            {isDraft ? 'Draft' : 'Complete'}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-3 text-sm">
          {isDecisionLog && isDraft ? (
            <Link
              href={`/entries/decision/${id}/complete` as never}
              className="inline-flex h-8 items-center rounded-md bg-primary px-3 font-medium text-primary-foreground shadow hover:bg-primary/90"
            >
              Complete this entry
            </Link>
          ) : null}
          {isDecisionLog ? (
            <Link
              href={`/entries/decision/${id}/outcome` as never}
              className="inline-flex h-8 items-center rounded-md border border-input bg-background px-3 font-medium hover:bg-accent"
            >
              {hasOutcome ? 'Edit outcome' : 'Add outcome'}
            </Link>
          ) : null}
          <Link
            href={'/entries/list' as never}
            className="text-primary underline-offset-4 hover:underline"
          >
            ← Back to entries
          </Link>
        </div>
      </header>

      <EntryDetailView detail={detail} />

      {type === 'comp_recap' ? (
        <section className="mt-6 grid gap-3 border-t border-border pt-4">
          <div>
            <h2 className="text-base font-semibold">Test Log trend (auto-generated)</h2>
            <p className="text-sm text-muted-foreground">
              Headline stats from Test Logs in the six weeks before this event, per series —
              generated by the app, no typing required.
            </p>
          </div>
          <TestTrendView series={trend} />
        </section>
      ) : null}

      {isDecisionLog && hasOutcome ? (
        <section className="mt-6 grid gap-4 border-t border-border pt-4">
          <h2 className="text-base font-semibold">Outcome</h2>
          {(
            [
              ['Actual outcome', outcome.actual_outcome],
              ['Delta from prediction', outcome.delta],
              ['What we learned', outcome.learned],
            ] as const
          ).map(([label, value]) =>
            value ? (
              <div key={label} className="grid gap-1">
                <h3 className="text-sm font-medium text-muted-foreground">{label}</h3>
                <p className="whitespace-pre-wrap text-sm">{value}</p>
              </div>
            ) : null,
          )}
        </section>
      ) : null}
    </main>
  );
}
