import type { EntryDefinition } from './_types';

export const outreachLogEntry: EntryDefinition = {
  type: 'outreach_log',
  table: 'outreach_logs',
  label: 'Outreach Log',
  description:
    'Every outreach event — demo, classroom visit, FLL coaching, community fair. ' +
    'Outreach Reporter does not run the demo; their job is to count, photograph, ' +
    'and capture stories. File within 24 hours.',
  fields: [
    {
      type: 'text',
      name: 'event_name',
      label: 'Event name',
      required: true,
      storage: 'column',
      maxLength: 200,
    },
    {
      type: 'date',
      name: 'event_date',
      label: 'Event date',
      required: true,
      storage: 'column',
      defaultValue: 'today',
    },
    {
      type: 'text',
      name: 'location_city',
      label: 'City',
      required: false,
      storage: 'column',
      maxLength: 100,
    },
    {
      type: 'text',
      name: 'location_state',
      label: 'State / region',
      required: false,
      storage: 'column',
      maxLength: 100,
    },
    {
      type: 'text',
      name: 'host_org',
      label: 'Host organization',
      required: false,
      storage: 'column',
      maxLength: 200,
    },
    {
      type: 'single-select',
      name: 'our_role_option_id',
      label: 'Our team’s role',
      category: 'our_role',
      allowAddNew: true,
      required: false,
      storage: 'column',
    },
    {
      type: 'single-select',
      name: 'event_type_option_id',
      label: 'Event type',
      category: 'event_type',
      allowAddNew: true,
      required: true,
      storage: 'column',
    },
    {
      type: 'text',
      name: 'outreach_reporter',
      label: 'Outreach Reporter (you)',
      required: true,
      storage: 'column',
      maxLength: 100,
    },
    {
      type: 'person-attribution',
      name: 'contributions',
      label: 'Team members present and their roles at the event',
      helper: 'One line per person — demonstrator, instructor, story capturer, setup, etc.',
      required: false,
      storage: 'extras',
      contributionLabel: 'Role at event',
      minRows: 0,
      maxRows: 30,
    },
    {
      type: 'number',
      name: 'total_attendees',
      label: 'Total attendees',
      unit: 'people',
      min: 0,
      max: 100000,
      required: true,
      storage: 'column',
    },
    {
      type: 'number',
      name: 'zero_first_count',
      label: 'Of those, number with zero prior FIRST experience',
      unit: 'people',
      min: 0,
      max: 100000,
      required: true,
      storage: 'column',
    },
    {
      type: 'text',
      name: 'age_range',
      label: 'Approximate age range',
      helper: 'e.g. "K–5", "middle school + parents", "mixed adult"',
      required: false,
      storage: 'column',
      maxLength: 100,
    },
    {
      type: 'multi-select',
      name: 'engagement_depth',
      label: 'Engagement depth — check all that apply',
      helper: 'At least one box OR a custom note describing the engagement.',
      category: 'engagement_depth',
      allowAddNew: true,
      withCustomNote: true,
      minSelected: 1,
      required: true,
      storage: 'extras',
    },
    {
      type: 'long-text',
      name: 'new_fll_participants',
      label: 'New FLL participants directly inspired today',
      helper: 'Names if known.',
      required: false,
      storage: 'extras',
      maxLength: 500,
      rows: 2,
    },
    {
      type: 'long-text',
      name: 'new_ftc_participants',
      label: 'New FTC participants directly inspired today',
      required: false,
      storage: 'extras',
      maxLength: 500,
      rows: 2,
    },
    {
      type: 'long-text',
      name: 'new_mentors',
      label: 'New mentors / coaches / volunteers committed today',
      required: false,
      storage: 'extras',
      maxLength: 500,
      rows: 2,
    },
    {
      type: 'long-text',
      name: 'existing_re_engaged',
      label: 'Existing FIRST community members re-engaged today',
      required: false,
      storage: 'extras',
      maxLength: 500,
      rows: 2,
    },
    {
      type: 'story-block',
      name: 'stories',
      label: 'Stories — minimum 3, named and permission-tracked',
      helper:
        'Each story: who, what happened (2–4 sentences), direct quote if any, ' +
        'permission status. Photo optional in Phase 1 (URL only).',
      required: true,
      storage: 'extras',
      minStories: 3,
      maxStories: 10,
    },
    {
      type: 'long-text',
      name: 'what_worked',
      label: 'What worked well',
      required: false,
      storage: 'column',
      maxLength: 1000,
      rows: 3,
    },
    {
      type: 'long-text',
      name: 'what_to_change',
      label: 'What we’d do differently next event',
      required: false,
      storage: 'column',
      maxLength: 1000,
      rows: 3,
    },
    {
      type: 'single-select',
      name: 'follow_up_type_option_id',
      label: 'Follow-up plan',
      helper: 'How will we follow up with people from this event? Pick one, or leave blank.',
      category: 'follow_up_type',
      allowAddNew: false,
      required: false,
      storage: 'column',
      display: 'radio',
    },
    {
      type: 'long-text',
      name: 'follow_up_individuals',
      label: 'Names for individual follow-up',
      helper:
        'List names. Each will become a Contact Log entry — flag them in the ' +
        '"Specialty entries triggered" section below.',
      required: false,
      storage: 'extras',
      visibleWhen: {
        field: 'follow_up_type_option_id',
        equalsOptionValue: 'individual',
        category: 'follow_up_type',
      },
      maxLength: 1000,
      rows: 4,
    },
    {
      type: 'long-text',
      name: 'follow_up_prior_outreach',
      label: 'Link to prior Outreach Log we’re re-engaging',
      helper: 'Paste the Outreach Log URL or ID.',
      required: false,
      storage: 'extras',
      visibleWhen: {
        field: 'follow_up_type_option_id',
        equalsOptionValue: 're-engagement',
        category: 'follow_up_type',
      },
      maxLength: 500,
      rows: 2,
    },
    {
      type: 'specialty-triggers',
      name: 'specialty_entries',
      label: 'Specialty entries triggered',
      helper: 'Most commonly a Contact Log for each new mentor / sponsor / individual follow-up.',
      storage: 'extras',
    },
  ],
};

export function listSummary(row: Record<string, unknown>): string {
  const event = String(row.event_name ?? 'Event');
  const attendees = row.total_attendees != null ? ` — ${row.total_attendees} attendees` : '';
  return `${event}${attendees}`.slice(0, 100);
}

export const outreachLogBodyMapping: Record<string, string> = {
  'team members present': 'contributions',
  'engagement depth': 'engagement_depth',
  'new fll participants directly inspired today': 'new_fll_participants',
  'new ftc participants directly inspired today': 'new_ftc_participants',
  'new mentors / coaches / volunteers committed today': 'new_mentors',
  'existing first community members re-engaged today': 'existing_re_engaged',
  stories: 'stories',
  'what worked well': 'what_worked',
  "what we'd do differently next event": 'what_to_change',
  'follow-up details': 'follow_up_individuals',
  'specialty entries triggered': 'specialty_entries',
};
